server:
  port: 8761
#spring:
#  rabbitmq:
#    host: ${rabbitmq.host:192.168.223.133}
#    port: ${rabbitmq.port:5672}
#    username: ${rabbitmq.username:admin}
#    password: ${rabbitmq.password:admin}
#  zipkin:
#    sender:
#      type: rabbit
#  sleuth:
#      web:
#        client:
#          enabled: true
#      sampler:
#        probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
