server:
  port: 11022
spring:
  application:
    name: landa-mas-zipkin-stream-client-backend
  rabbitmq:
    host: ${rabbitmq.host:192.168.223.133}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:admin}
    password: ${rabbitmq.password:admin}
  zipkin:
    sender:
      type: rabbit
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0

## cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true